language: java
jdk:
  - oraclejdk8
services:
  - mysql
  - redis-server
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - sudo mysql_upgrade --force
  - sudo service mysql restart
install:
  - cd skill6-parent
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - \"skill6.mysql.passwrod\"=
    - \"skill6.mysql.url\"="jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8"
    - \"skill6.mysql.username\"=root
    - \"skill6.redis.host\"=localhost
    - \"skill6.redis.password\"=
    - \"skill6.redis.port\"=6379
