version: '3.1'
services:
  skill6-website:
    container_name: skill6-website
    image: skill6-website:0.0.1-SNAPSHOT
    ports:
    - 9081:8081
    restart: always
  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
    - 80:80
    - 443:443
    depends_on:
    - skill6-website
    restart: always