server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
      - image/png
      - image/jpeg
      - image/jpg
spring:
  application:
    name: skill6-website
  datasource:
    username: ${SKILL6_MYSQL_USERNAME}
    password: ${SKILL6_MYSQL_PASSWROD}
    url: ${SKILL6_MYSQL_URL}
    druid:
      name: skill6-mysql-01
    schema: classpath*:schema/init_db.sql
    initialization-mode: always
  redis:
    host: ${SKILL6_REDIS_HOST}
    password: ${SKILL6_REDIS_PASSWORD}
    port: ${SKILL6_REDIS_PORT}
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis:
  config-location: classpath:mybatis/mybatis-spring-config.xml
  mapper-locations: classpath*:mappers/**/*.xml
logging:
  level:
    root: INFO
    cn.skill6.website.dao: DEBUG
  path: /Users/liujichun/Downloads/elk/log/